version: '3'

volumes:

  bundle:
  node_modules:

services:

  web:
    build:    .
    env_file: .env
    command:  rake server
    ports:
      - 4567:4567
      - 35729:35729
    volumes:
      - .:/la_lavandera
      - node_modules:/la_lavandera/node_modules
      - bundle:/bundle
